version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: streaming-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_DATABASE:-streaming_app}
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: streaming-redis
    restart: always
    ports:
      - '6379:6379'

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streaming-server
    ports:
      - '${SERVER_PORT:-3000}:3000'
    environment:
      SERVER_PORT: ${SERVER_PORT:-3000}
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: ${DB_USERNAME:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      DB_DATABASE: ${DB_DATABASE:-streaming_app}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      R2_ACCESS_KEY_ID: ${R2_ACCESS_KEY_ID}
      R2_SECRET_ACCESS_KEY: ${R2_SECRET_ACCESS_KEY}
      R2_S3_API: ${R2_S3_API}
      R2_BUCKET_NAME: ${R2_BUCKET_NAME}
      # CHOKIDAR_USEPOLLING: 'true'
      # WATCHPACK_POLLING: 'true'
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules

volumes:
  postgres_data:
  node_modules:
